<a href="https://colab.research.google.com/github/lutherleo/MLClass/blob/main/Copy_of_MLSp25_Matrix_Demo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy 2D Arrays (aka matrices)

In the previous demos and labs we worked with 1 dimensional ndarrays. Moving forward, we need to work with matrix data, which in numpy are represented as 2 dimensional arrays.

As usual, we begin by loading the `numpy` package.

They we show a simple example of how to create a 2-d array (aka a matrix).

In [ ]:
import numpy as np
X = np.array([[0,1],[2,3],[4,5]])
print(X)

[[0 1]
 [2 3]
 [4 5]]


You can check `X`'s dimensions using the `shape` variable. Do this often! One of the most common mistakes is having a dimension mismatch.

numpy also hands vectors in a sloppy way. There are both 1-d arrays with no second dimension, and 2-d arrays with one of the dimensions equalt to 1. Be aware!

In [ ]:
X.shape

(3, 2)

In [ ]:
y = np.array([6,7])
y.shape

(2,)

In [ ]:
y = np.array([[6],[7]])
y.shape

(2, 1)

To make a 1-d into a 2-d array with dimension one, use the `None` operation. You can either create a row or column vector.

In [ ]:
y = np.array([6,7])
print(y[None,:].shape)
print(y[:,None].shape)

(1, 2)
(2, 1)


We can perform basic operations on the matrix, like take its transpose, or sum up all elements.

In [ ]:
Y = np.transpose(X)
print(Y)

[[0 2 4]
 [1 3 5]]


In [ ]:
np.sum(X)

15

We can also use slice indexing, just like we did for vectors. Note that in the last example we are grabbing the first column from the matrix. This gets returned as a 1-d array, not a 2-d array with second dimenion 1.

In [ ]:
print(X);print()
print(X[0,0]);print()
print(X[0,1]);print()
print(X[1,0]);print()
print(X[0:2,0]);print()
print(X[:,0]);print()


[[0 1]
 [2 3]
 [4 5]]

0

1

2

[0 2]

[0 2 4]



## Axis Parameter

Many operations in the `numpy` package can take an optional `axis` parameter to specify which dimensions the operation is to be applied.  This is extremely useful for multi-dimensional data. An operation like `np.mean` or `np.sum` takes the mean or sum of *all* elements in the array -- from all rows and columns.

In [ ]:
print(np.mean(X))
print(np.sum(X))

2.5
15


To take only the `sum` along each column, we can use the `axis` parameter.

In [ ]:
print(X)
print(np.sum(X,axis=0))

[[0 1]
 [2 3]
 [4 5]]
[6 9]


Since `X` has shape `(3,2)`, the output `np.sum(X,axis=0)` is of shape `(2,)`.  Similarly, we can take the `sum` along each row:

In [ ]:
print(np.sum(X,axis=1))

[1 5 9]


## Broadcasting

**Broadcasting** is a useful tool in Python for performing operations on matrices. It generalizes the useful fact that, if we multiply a numpy array by a scalar, Python knows that we want to multiply *every entry* by that scalar.  

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
b = 2
print(b*a)
print(a*b)

[[ 2  4  6]
 [ 8 10 12]]
[[ 2  4  6]
 [ 8 10 12]]


### Example 1:  Mean Removal

Suppose that `X` is a data matrix of shape `(n,d)`.  That is, there are `n` data points and `d` features per point.  Often, we have to remove the mean from each feature.  That is, we want to compute the mean for each feature and then remove the mean from each column.  We could do this with a for-loop as:

In [ ]:
# Generate some random data
n = 100
d = 5
X = np.random.rand(n,d)
print(X[0:7,:]) # print the first several rows of X

[[0.16685458 0.26976574 0.37489954 0.79544607 0.75364133]
 [0.81798937 0.65779237 0.2374753  0.13729017 0.12583327]
 [0.98116558 0.39248653 0.95431359 0.41876647 0.92121877]
 [0.92754284 0.69713393 0.77888691 0.62912961 0.83298338]
 [0.83307305 0.77424891 0.75824912 0.40239156 0.15108809]
 [0.45220829 0.28918228 0.46370073 0.83877209 0.37082846]
 [0.05611794 0.30852591 0.27443029 0.54924452 0.08512761]]


In [ ]:
Xm = np.zeros(d)      # Mean for each feature
X_demean = np.zeros((n,d))  # Transformed features with the means removed
for j in range(d):
    Xm[j] = np.mean(X[:,j])
    for i in range(n):
        X_demean[i,j] = X[i,j] - Xm[j]
print(X_demean[0:7,:]) # print the first several rows of the result to compare to later

[[-0.33307528 -0.21816042 -0.13095583  0.27095632  0.21487218]
 [ 0.31805951  0.16986621 -0.26838007 -0.38719958 -0.41293589]
 [ 0.48123572 -0.09543963  0.44845823 -0.10572328  0.38244962]
 [ 0.42761298  0.20920777  0.27303155  0.10463986  0.29421423]
 [ 0.33314318  0.28632274  0.25239375 -0.12209819 -0.38768107]
 [-0.04772157 -0.19874389 -0.04215464  0.31428233 -0.16794069]
 [-0.44381193 -0.17940025 -0.23142508  0.02475477 -0.45364154]]


The code below does this without a for loop using the `axis` parameter and broadcasting.

In [ ]:
# Compute the mean per column using the axis command
Xm = np.mean(X,axis=0)  # This is a d-dim matrix
print(Xm)

[0.49992986 0.48792616 0.50585537 0.52448975 0.53876916]


To use broadcasting we will need to convert Xm to a 2 dimensional ndarray. As show before, we can do this with the `Xm[None,:]` operation, which returns a `(1,d)` shape array.

In [ ]:
print(Xm[None,:])

[[0.49992986 0.48792616 0.50585537 0.52448975 0.53876916]]


Using Python broadcasting, we can then subtract the `Xm[None,:]` from `X`. These array are different sizes -- `Xm[None,:]` has one row while `X` has n. But numpy automatically figures out that, since the number of columns match, we want to substract `Xm[None,:]` off of every row in X.

In [ ]:
# Subtract the mean
X_demean = X - Xm[None,:]
print(X_demean[0:7,:])

[[-0.33307528 -0.21816042 -0.13095583  0.27095632  0.21487218]
 [ 0.31805951  0.16986621 -0.26838007 -0.38719958 -0.41293589]
 [ 0.48123572 -0.09543963  0.44845823 -0.10572328  0.38244962]
 [ 0.42761298  0.20920777  0.27303155  0.10463986  0.29421423]
 [ 0.33314318  0.28632274  0.25239375 -0.12209819 -0.38768107]
 [-0.04772157 -0.19874389 -0.04215464  0.31428233 -0.16794069]
 [-0.44381193 -0.17940025 -0.23142508  0.02475477 -0.45364154]]


### Example 2:  Standardizing variables

A variant of the above example is to *standardize* the features, where we compute the transform variables,

    Z[i,j] = (X[i,j] - Xm[j])/ Xstd[j]
    
where `Xstd[j]` is the standard deviation per feature.  This can be done as follows:

In [ ]:
Xstd = np.std(X,axis=0)
Z = (X-Xm[None,:])/Xstd[None,:]

**Exercise 1:**  Given a matrix `X`, compute the matrix `Y`, where the rows of `X` are normaized to have norm one.  That is:

     Y[i,j] = X[i,j] / sum_j X[i,j]   

In [ ]:
X = np.random.rand(4,3)
# Y = ...

**Exercise 2:** Diagonal multiplication.  Given a matrix `X` and a vector `d`, compute `Y = diag(d)*X`.

In [ ]:
X = np.random.rand(5,3)
d = np.random.rand(5)
# Y = ...

## Matrix operations with numpy
Python broadcasting is great, but sometime it does exactly the wrong thing. If you have a column vector `z` and a matrix `X`, `X*z` won't compute the matrix-vector product, but rather use broadcasting to scales `X`'s rows. Or it will throw an error if the dimensions don't work out. Similarly for matrix `X` and `Y`, `X*Y` does not compute a matrix product.

In [ ]:
X = np.array([[1,2],[3,4]])
z = np.array([[2],[3]])
Y = np.array([[-1,-1],[-1,-1]])
print(X);print()
print(z);print()
print(Y);print()

[[1 2]
 [3 4]]

[[2]
 [3]]

[[-1 -1]
 [-1 -1]]



In [ ]:
print(str(X*z));print()
print(X*Y)

[[ 2  4]
 [ 9 12]]

[[-1 -2]
 [-3 -4]]


To compute actually matrix/matrix and matrix/vector products, you can use the `dot` operation.

In [ ]:
print(np.dot(X,z));print()
print(np.dot(np.transpose(z),z));print()
print(np.dot(X,Y));print()

[[ 8]
 [18]]

[[13]]

[[-3 -3]
 [-7 -7]]



The nameing of the `dot` command is unfortunate because it doesn't actually perform a dot product! If you run np.(z,z) you will get an error, even then $\langle z,z\rangle$ is a valid linear algebra operation.

Fortunately, you can avoid `dot` altogether. A much cleaner approach is to use numpy's `@` operator. This operator works directly on 2D ndarrays with compatible dimensions.

In [ ]:
print(X@z);print()
print(np.transpose(z)@z);print()
print(X@Y)

[[ 8]
 [18]]

[[13]]

[[-3 -3]
 [-7 -7]]


Note that `@` between a row and column vector computes an outerproduct instead of an inner product.

In [ ]:
print(z@np.transpose(z))

[[4 6]
 [6 9]]


The @ command can be used with vectors that are 1-d not 2-d arrays. For example, the following code is valid. But not the output is a 1-d, not a 2-d array

In [ ]:
X = np.array([[1,2],[3,4],[5,6]])
z = np.array([2,3])
w = np.array([2,3,4])
print(X@z)
print()
print(w@X)

[ 8 18 28]

[31 40]
